В этом блокнотике я выписал только базовые операции из библиотеки. Чтобы разобрать все, потребуется очень много времени, да и нужно ли это?

### Установка и импорт
`NumPy` - нестандартная библиотека, поэтому ее нужно установить.

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

### Особенности библиотеки и первые строки кода.

Безусловно, `numpy` - одна из самых распространенных библиотек для Python. Она частично написана на низкоуровневых языках `C` и `Fortran`, поэтому умеет очень быстро выполняться. Для этой библиотеки специфичен специальный тип данных - `Array`. По сравнению с обычным питоновским `list`, он способен хранить очень много значений, но платит за это хранением лишь одного типа данных.

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]


Сразу хочу отметить про размерность массивов. В документации они называются осями - `axis`. Итак, массив `a` имеет одну ось длиной в 4 элемента, а массив `b` - две оси: первая(вертикальная) длиной 3 элемента и вторая(горизонтальная) на 2 элемента соответственно.

Количество осей;
Размер матрицы `MxN`;
Общее количество элементов;
Тип данных элементов массива;
Занимаемый одним элементом объем памяти;

In [25]:
a.ndim,\
b.shape,\
b.size,\
b.dtype,\
b.itemsize

(1, (3, 2), 6, dtype('int64'), 8)

Создание массива с нестандартным типом данных:

In [26]:
a = np.array([1, 2], dtype="uint8")

А что будет, если пытаться создать массив с числами и строками?

In [28]:
c = np.array(['123', 'text', 1, 2, 2.5])
print(c, c.dtype)

['123' 'text' '1' '2' '2.5'] <U32


Он просто перевел числа в строки!

Часто используемые способы задать матрицу:

In [32]:
print(np.ones((5, 6)), np.zeros((4, 3)), np.eye(7, 9), sep='\n\n')

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]]


Если нужно создать стандартные матрицы на основе уже имеющейся:

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.zeros_like(A), np.ones_like(A), sep= '\n\n')

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Функция `arange`, похожая на стандартную `range`, только возвращающую массив:

In [33]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(0.5, 9.5, 1.5)

array([0.5, 2. , 3.5, 5. , 6.5, 8. ])

Функция `linspace()`, думаю по коду понятно, что она делает:

In [35]:
np.linspace(1, 5, 4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [36]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
np.linspace(1, -8, 10)

array([ 1.,  0., -1., -2., -3., -4., -5., -6., -7., -8.])

Изменения размеров.
Функция `reshape` выдает новый массив. Функция `resize` меняет размерность исходного массива.

In [44]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)
print()
print(a.reshape(4, 2))
print()
print(a.reshape(4, 2).reshape(2, 4))
print()
print(a.reshape(4, 2))
print()
print(a)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 3 4]
 [5 6 7 8]]


In [47]:
a.resize(2, 2, 2)
print(a) #трехмерная матрица

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Можно указать в `reshape()` указать в качестве параметра `-1`, то параметр под эту ось рассчитается автоматически.

### Математические операции над массивами

Доступно все, делается все поэлементно. Операции с массивами происходят при их одинаковой размерности.

In [48]:
a = np.array([1, 2, 3])
b = np.array([9, 8, 7])
print(a + b, a - b, a * b, a / b, sep='\n\n')

[10 10 10]

[-8 -6 -4]

[ 9 16 21]

[0.11111111 0.25       0.42857143]


Для математического умножения доступна операция `@` или `dot`.

In [59]:
a = np.eye(3, 3)
print(a)
b = np.eye(3, 3, 1)
print(b)
print()
print(a @ b, a.dot(b), sep='\n\n')

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


`transpose()` и `np.rot90(a)` транспонирует и поворачивает матрицу на `90 градусов`.

`sum`, `min`, `max`, `avg` тоже работают.

Кванторы $\forall \text{ и } \exist$:

In [7]:
c = np.array([True] * 5)
d = np.array([False, False])
e = np.array([True, False])
np.all(c), np.all(d), np.all(e), np.any(c), np.any(d), np.any(e)

(True, False, False, True, False, True)

Часто используется кумулятивная сумма:

In [9]:
a = np.random.randint(1, 10, 5)
print(a)
print(np.cumsum(a))

[4 5 4 9 5]
[ 4  9 13 22 27]


### Изменения массивов

1. Сортировка возвращает новый массив.
2. Объединение массивов.
3. Разбиение массивов в заданных точках.

In [16]:
print(a)
print(np.sort(a))
print(c)
print(d)
print(np.hstack((c, d)))
print(np.hsplit(c, [1, 2]))

[4 5 4 9 5]
[4 4 5 5 9]
[ True  True  True  True  True]
[False False]
[ True  True  True  True  True False False]
[array([ True]), array([ True]), array([ True,  True,  True])]


Функции `delete`, `insert` и `append` возвращают новые массивы:

In [24]:
print(a)
print(np.delete(a, [0, 4])) #индексы
print(np.insert(a, [1, 2], [2, 3]))
print(np.append(a, [1, 2, 3, 4]))

[4 5 4 9 5]
[5 4 9]
[4 2 5 3 4 9 5]
[4 5 4 9 5 1 2 3 4]


Здесь происходит передача массива по ссылке, а дальше показано, как копировать массив:

In [28]:
print(a)
b = a[:]
print(b)
b[0] = 10
print(a)

[10  5  4  9  5]
[10  5  4  9  5]
[10  5  4  9  5]


In [ ]:
print(a)
b = a[:]
print(b)
b[0] = 10
print(a)

[10  5  4  9  5]
[10  5  4  9  5]
[10  5  4  9  5]


In [30]:
b = a.copy()
b[0] = 0
print(b)
print(a)

[0 5 4 9 5]
[10  5  4  9  5]


### Передача оси в качестве аргумента функции.

Все постоянно путаются, какая ось за что отвечает. Ось 0 или `axis=0` отвечает за вертикальный лифт, то есть, если мы по ней двигаемся, то считаем строки. Ось 1 или `axis=1` отвечает за горизонтальный лифт (считаем столбцы). Вот примеры на понимание:

In [64]:
a = np.arange(1, 10).reshape(3, 3)
print(a)
print()
print(a.sum(axis=0))  # сумма чисел в каждом столбце
print(a.sum(axis=1))  # сумма чисел в каждой строке
print(a.min(axis=0))  # минимум по столбцам
print(a.max(axis=1))  # максимум по строкам

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[12 15 18]
[ 6 15 24]
[1 2 3]
[3 6 9]


### Перевод в одномерный массив.

На самом деле все массивы из `numpy` хранятся одномерно в памяти.

`flat` делает любую матрицу одномерной:

In [66]:
print(a)
print([elem for elem in a.flat])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


### Линейная алгебра

За это отвечает пакет `numpy.linalg`.

Начнем с определителя матрицы.

In [9]:
a = np.array([-9, -4, 3, 2, 10, 12, 29, 0, 22]).reshape(3, 3)
print(a)
print(np.linalg.det(a))

[[-9 -4  3]
 [ 2 10 12]
 [29  0 22]]
-4066.0000000000014


Продолжим обратной матрицей:

In [10]:
np.linalg.inv(a)

array([[-0.05410723, -0.02164289,  0.01918347],
       [-0.07476636,  0.07009346, -0.02803738],
       [ 0.07132317,  0.02852927,  0.02016724]])

Решение системы $A*\vec{x} = \vec{v}$:

In [25]:
x = np.linalg.solve(a, [1, 2, 3])
print(x)
# Проверим
np.all(np.round(a @ x - [1, 2, 3]) == 0)

[-0.0398426  -0.01869159  0.18888342]


True

Собственные значения и собственные векторы. Обозначнения из уравнения $A * \vec{x}_i = \lambda_i * \vec{x}_i$:

In [28]:
lambdas, x = np.linalg.eig(a)
print(lambdas)
print()
print(x)

[-12.88749125  20.48899172  15.39849953]

[[ 0.7428067   0.03443904  0.09598035]
 [ 0.25882371 -0.74962109 -0.90167115]
 [-0.61745323 -0.66097063 -0.421636  ]]


Функция `diag` работает в две стороны: из одномерного массива строит диагональную матрицу и из матрицы достает диагональные элементы в одномерный массив.

In [35]:
print(a)
print(np.diag(a))
print(np.diag(np.diag(a)))
print(np.diag(np.diag(a), k=1))
print(np.diag(np.diag(a), k=-1))

[[-9 -4  3]
 [ 2 10 12]
 [29  0 22]]
[-9 10 22]
[[-9  0  0]
 [ 0 10  0]
 [ 0  0 22]]


TypeError: diag() got an unexpected keyword argument 'size'

### Интегрирование

In [37]:
from scipy.integrate import quad, odeint
from scipy.special import erf

In [45]:
def f(x):
    return 1/np.sqrt(2 * np.pi) * np.exp(-x**2/2)

Интегрирование на отрезке от `a` до `b`. `res` - результат интегрирования, `err` - погрешность.

In [47]:
a = -np.inf
b = np.inf
res, err = quad(f, a, b)
res_, err_ = quad(f, 0, b)
print(res, err, res_, err_)

0.9999999999999997 1.0178191380347127e-08 0.49999999999999983 5.089095690173563e-09


### Сохранение в файл и чтение из файла

In [49]:
print(x)

[[ 0.7428067   0.03443904  0.09598035]
 [ 0.25882371 -0.74962109 -0.90167115]
 [-0.61745323 -0.66097063 -0.421636  ]]


In [52]:
np.savetxt('123.txt', x, fmt='%.2f', delimiter=';')
!cat 123.txt

0.74;0.03;0.10
0.26;-0.75;-0.90
-0.62;-0.66;-0.42


In [55]:
y = np.loadtxt('123.txt', delimiter=';')
y

array([[ 0.74,  0.03,  0.1 ],
       [ 0.26, -0.75, -0.9 ],
       [-0.62, -0.66, -0.42]])