### Установка и импорт
`NumPy` - нестандартная библиотека, поэтому ее нужно установить.

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

### Особенности библиотеки и первые строки кода.

Безусловно, `numpy` - одна из самых распространенных библиотек для Python. Она частично написана на низкоуровневых языках `C` и `Fortran`, поэтому умеет очень быстро выполняться. Для этой библиотеки специфичен специальный тип данных - `Array`. По сравнению с обычным питоновским `list`, он способен хранить очень много значений, но платит за это хранением лишь одного типа данных.

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]


Сразу хочу отметить про размерность массивов. В документации они называются осями - `axis`. Итак, массив `a` имеет одну ось длиной в 4 элемента, а массив `b` - две оси: первая(вертикальная) длиной 3 элемента и вторая(горизонтальная) на 2 элемента соответственно.

Количество осей;
Размер матрицы `MxN`;
Общее количество элементов;
Тип данных элементов массива;
Занимаемый одним элементом объем памяти;

In [25]:
a.ndim,\
b.shape,\
b.size,\
b.dtype,\
b.itemsize

(1, (3, 2), 6, dtype('int64'), 8)

Создание массива с нестандартным типом данных:

In [26]:
a = np.array([1, 2], dtype="uint8")

А что будет, если пытаться создать массив с числами и строками?

In [28]:
c = np.array(['123', 'text', 1, 2, 2.5])
print(c, c.dtype)

['123' 'text' '1' '2' '2.5'] <U32


Он просто перевел числа в строки!

Часто используемые способы задать матрицу:

In [32]:
print(np.ones((5, 6)), np.zeros((4, 3)), np.eye(7, 9), sep='\n\n')

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]]


Функция `arange`, похожая на стандартную `range`, только возвращающую массив:

In [33]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(0.5, 9.5, 1.5)

array([0.5, 2. , 3.5, 5. , 6.5, 8. ])

Функция `linspace()`, думаю по коду понятно, что она делает:

In [35]:
np.linspace(1, 5, 4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [36]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
np.linspace(1, -8, 10)

array([ 1.,  0., -1., -2., -3., -4., -5., -6., -7., -8.])

Изменения размеров.
Функция `reshape` выдает новый массив. Функция `resize` меняет размерность исходного массива.

In [44]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)
print()
print(a.reshape(4, 2))
print()
print(a.reshape(4, 2).reshape(2, 4))
print()
print(a.reshape(4, 2))
print()
print(a)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 3 4]
 [5 6 7 8]]


In [47]:
a.resize(2, 2, 2)
print(a) #трехмерная матрица

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Можно указать в `reshape()` указать в качестве параметра `-1`, то параметр под эту ось рассчитается автоматически.

### Математические операции над массивами

Доступно все, делается все поэлементно. Операции с массивами происходят при их одинаковой размерности.

In [48]:
a = np.array([1, 2, 3])
b = np.array([9, 8, 7])
print(a + b, a - b, a * b, a / b, sep='\n\n')

[10 10 10]

[-8 -6 -4]

[ 9 16 21]

[0.11111111 0.25       0.42857143]


Для математического умножения доступна операция `@` или `dot`.

In [59]:
a = np.eye(3, 3)
print(a)
b = np.eye(3, 3, 1)
print(b)
print()
print(a @ b, a.dot(b), sep='\n\n')

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


`transpose()` и `np.rot90(a)` транспонирует и поворачивает матрицу на `90 градусов`.

`sum`, `min`, `max`, `avg` тоже работают.

### Передача оси в качестве аргумента функции.

Все постоянно путаются, какая ось за что отвечает. Ось 0 или `axis=0` отвечает за вертикальный лифт, то есть, если мы по ней двигаемся, то считаем строки. Ось 1 или `axis=1` отвечает за горизонтальный лифт (считаем столбцы). Вот примеры на понимание:

In [64]:
a = np.arange(1, 10).reshape(3, 3)
print(a)
print()
print(a.sum(axis=0))  # сумма чисел в каждом столбце
print(a.sum(axis=1))  # сумма чисел в каждой строке
print(a.min(axis=0))  # минимум по столбцам
print(a.max(axis=1))  # максимум по строкам

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[12 15 18]
[ 6 15 24]
[1 2 3]
[3 6 9]


### Завершение

`flat` делает любую матрицу одномерной:

In [66]:
print(a)
print([elem for elem in a.flat])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [73]:
x, y = [float(x) for x in input().split(' ')]
print(x, y)

1.0 2.0


In [150]:
vector = np.arange(5)
n = vector.size
result = []
result += [vector.tolist()]
result += [[result[0][-1]] + result[0][0:-1]]
print(result)

[[0, 1, 2, 3, 4], [4, 0, 1, 2, 3]]
